framework:
  webhook:
    routing:
      getvideosuccess:
        service: App\Presentation\Webhook\Core\GetVideoSuccessRequestParser
        secret: '%env(CORE_TOKEN)%'
      getvideofailure:
        service: App\Presentation\Webhook\Core\GetVideoFailureRequestParser
        secret: '%env(CORE_TOKEN)%'
      extractsoundsuccess:
        service: App\Presentation\Webhook\Core\ExtractSoundSuccessRequestParser
        secret: '%env(CORE_TOKEN)%'
      extractsoundfailure:
        service: App\Presentation\Webhook\Core\ExtractSoundFailureRequestParser
        secret: '%env(CORE_TOKEN)%'
      generatesubtitlesuccess:
        service: App\Presentation\Webhook\Core\GenerateSubtitleSuccessRequestParser
        secret: '%env(CORE_TOKEN)%'
      generatesubtitlefailure:
        service: App\Presentation\Webhook\Core\GenerateSubtitleFailureRequestParser
        secret: '%env(CORE_TOKEN)%'
      transformsubtitlesuccess:
        service: App\Presentation\Webhook\Core\TransformSubtitleSuccessRequestParser
        secret: '%env(CORE_TOKEN)%'
      transformsubtitlefailure:
        service: App\Presentation\Webhook\Core\TransformSubtitleFailureRequestParser
        secret: '%env(CORE_TOKEN)%'
      resizevideosuccess:
        service: App\Presentation\Webhook\Core\ResizeVideoSuccessRequestParser
        secret: '%env(CORE_TOKEN)%'
      resizevideofailure:
        service: App\Presentation\Webhook\Core\ResizeVideoFailureRequestParser
        secret: '%env(CORE_TOKEN)%'
      embedvideofailure:
        service: App\Presentation\Webhook\Core\EmbedVideoFailureRequestParser
        secret: '%env(CORE_TOKEN)%'
      embedvideosuccess:
        service: App\Presentation\Webhook\Core\EmbedVideoSuccessRequestParser
        secret: '%env(CORE_TOKEN)%'
      chunkvideosuccess:
        service: App\Presentation\Webhook\Core\ChunkVideoSuccessRequestParser
        secret: '%env(CORE_TOKEN)%'
      chunkvideofailure:
        service: App\Presentation\Webhook\Core\ChunkVideoFailureRequestParser
        secret: '%env(CORE_TOKEN)%'
      resumevideosuccess:
        service: App\Presentation\Webhook\Core\ResumeVideoSuccessRequestParser
        secret: '%env(CORE_TOKEN)%'
      resumevideofailure:
        service: App\Presentation\Webhook\Core\ResumeVideoFailureRequestParser
        secret: '%env(CORE_TOKEN)%'
      createcheckout:
        service: App\Presentation\Webhook\Payment\CreateCheckoutRequestParser
        secret: '%env(STRIPE_WEBHOOK_CHECKOUT_KEY)%'
      subscriptionupdated:
        service: App\Presentation\Webhook\Payment\SubscriptionUpdatedRequestParser
        secret: '%env(STRIPE_WEBHOOK_SUBSCRIPTION_UPDATED_KEY)%'
      subscriptiondeleted:
        service: App\Presentation\Webhook\Payment\SubscriptionDeletedRequestParser
        secret: '%env(STRIPE_WEBHOOK_SUBSCRIPTION_DELETED_KEY)%'
