controllers:
    resource:
        path: ../src/Core/Presentation/Controller/
        namespace: App\Core\Presentation\Controller
    type: attribute

token:
    path: /api/token
    methods: [ "POST" ]
    